# generated by Google 2026-06-02
# https://www.google.com/search?client=firefox-b-d&q=automatically+enhance+page+images+for+ocr&udm=50&fbs=ADc_l-aN0CWEZBOHjofHoaMMDiKpaEWjvZ2Py1XXV8d8KvlI3p-ML-906rRL_m6h4jR-tdCeKIwp94h-QiJ4lJfObsqUPixp6KuAej6LdEw-ul8fud3FiyoYcNHDn3HZ8mQ6T-ckdOlkfthMcAd5uMRwsZYjn_umCTETpZ0MlqjQ3jj6aU2YNhF3WIfCt5zMJugIboT7gnQP7QtzrBFLK8H8LGGlhRBepA&aep=10&ntc=1&mstk=AUtExfAYD_fjAaUnYfqfPPG0HcXOpCOyzQEbtmtJWY3M0Y7f5ZX9SmI2zIXOGjBB79wJX6GRHFlwr5HRDV0ydA0bNQ0MdxTvfdmgrm0S9lCLFgFzkiWXhnu3WmfN7UVFmJK3kkCBvi3bUNzqtuUNp0pZEL8SNtbOkEm6HolQDUGjwfEUalM5n5roUf5Saj74C-YOD4fHj8C69FnolTAUaCo21GA8FdSwgTjhAUgJsmSO5C16b4ATlzFKYN4gHQ&aioh=3&csuir=1&mtid=6D4favrmJ5z40PEPzvuGIA

import base64
import json
import cv2
import requests


def enhance_image_for_ollama(image_path):
    """Loads, deskews, denoises, and sharpens an image for a Vision Model."""
    # 1. Load image in grayscale first to analyze rotation
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 2. De-skewing (Auto-rotation)
    coords = cv2.findNonZero(cv2.bitwise_not(gray))
    angle = cv2.minAreaRect(coords)[-1]
    if angle < -45:
        angle = -(90 + angle)
    elif angle > 45:
        angle = 90 - angle
    else:
        angle = -angle

    if abs(angle) > 0.5:  # Rotate only if significantly crooked
        h, w = img.shape[:2]
        center = (w // 2, h // 2)
        M = cv2.getRotationMatrix2D(center, angle, 1.0)
        img = cv2.warpAffine(
            img, M, (w, h), flags=cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE
        )

    # 3. Denoising (Removes paper grain/noise while preserving edges)
    denoised = cv2.fastNlMeansDenoisingColored(
        img, None, h=3, hColor=3, templateWindowSize=7, searchWindowSize=21
    )

    # 4. Contrast & Sharpness Boost (Using CLAHE on Luminance channel)
    lab = cv2.cvtColor(denoised, cv2.COLOR_BGR2LAB)
    l_channel, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    cl = clahe.apply(l_channel)
    enhanced_lab = cv2.merge((cl, a, b))
    enhanced_bgr = cv2.cvtColor(enhanced_lab, cv2.COLOR_LAB2BGR)
    enhanced_greyscale = cv2.cvtColor(enhanced_bgr, cv2.COLOR_BGR2GRAY)

    # save the image
    success = cv2.imwrite('output_image.png', enhanced_greyscale)
    print("output_image.png saved")

    # Encode the processed image directly to memory buffer
    _, buffer = cv2.imencode(".png", enhanced_greyscale)
    return base64.b64encode(buffer).decode("utf-8")


def run_ollama_ocr(image_path, model_name="llama3.2-vision", url="http://localhost:11434/api/generate"):
    """Sends the enhanced image to Ollama's REST API."""
    print("Processing and enhancing image...")
    base64_image = enhance_image_for_ollama(image_path)

    payload = {
        "model": model_name,
        "prompt": "Act as a precise OCR engine. Transcribe all the headlines from this image of a newspaper page exactly as they appear. Maintain formatting and reading order. Do not transcribe the text of the articles. Complete each column before moving on to the next column. Do not explain, summarize, or chat.",
        "images": [base64_image],
        "stream": False,  # Set to True if you want to handle streaming responses
        "options": {
            "temperature": 0.0  # Force deterministic output for higher accuracy
        },
    }

    print(f"Sending request to Ollama ({model_name})...")
    try:
        response = requests.post(
            url, data=json.dumps(payload), headers={"Content-Type": "application/json"}
        )
        response.raise_for_status()
        result = response.json()
        return result.get("response", "")
    except requests.exceptions.RequestException as e:
        return f"API Error: {e}"


# --- Execution ---
if __name__ == "__main__":
    # Replace with your actual image path
    input_image = "/Users/pbinkley/Downloads/radiator-2-17-01.jpg"

    # Common Ollama vision models: 'llama3.2-vision' or 'minicpm-v'
    extracted_text = run_ollama_ocr(input_image, model_name="llama3.2-vision")

    print("\n--- Extracted Text ---")
    print(extracted_text)
